# Generated by Django 3.2.9 on 2021-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211205_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numReview',
            new_name='numReviews',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
