products = [
    {
        '_id': '1',
        'name': 'Agile Software Development: From Beginner to Practicioner',
        'image': '/images/intro_to_agile.jpg',
        'description':
        'Learn why and when you should use agile, how to be agile,understanding and applying Extreme Programming (XP) practices,collaborating, releasing, planning, developing, processimprovement, identify and elimante waste, and how to seektechincal excellence.Includes 20 hours of video instruction, text book, course workbook, templates for getting started, and 4 weekly group coaching calls.',
        'instructor': 'Luca Leyva',
        'category': 'Agile',
        'price': 699.99,
        'countInStock': 100,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Scrum: From Beginner to Practicioner',
        'image': '/images/scrum.jpg',
        'description':
        'Learn how to use Scrum to deliver higher quality products thatcustomers love at a quicker rate.Includes 10 hours of video instruction, text book, course workbook, templates for getting started, and 2 coaching.',
        'instructor': 'Luca Leyva',
        'category': 'Agile',
        'price': 350,
        'countInStock': 10,
        'rating': 5.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Lean: From Beginner to Practicioner',
        'image': '/images/Lean.jpg',
        'description':
        'Learn how to use Lean to reduce waste, increse alignment andautonomy, and deliver high qulaity products as a much fasterpace.Includes 20 hours of video instruction, text book, course workbook, templates for getting started, and 4 weekly group coaching calls.',
        'instructor': 'Luca Leyva',
        'category': 'Lean',
        'price': 699.99,
        'countInStock': 10,
        'rating': 5.0,
        'numReviews': 8,
    },
    {
        '_id': '4',
        'name': 'Applied Systems Thinking: From Beginner to Practicioner',
        'image': '/images/systems_thinking.jpg',
        'description':
        'Learn how to see and understand the various systems at your workplace, how to influence systmic change, and how to train up other systems thinkers. Includes 3 months of live weekly coaching calls, a text book, course workbook, and templates for getting started.',
        'instructor': 'Luca Leyva',
        'category': 'Systems Thinking',
        'price': 1299.99,
        'countInStock': 10,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Kanban: From Beginner to Practicioner',
        'image': '/images/kanban.jpg',
        'description':
        'Learn how to visualize your work, identify the various "time theifs" and how to address them, and achieve a sustainable delivery pace. Includes a 10 hours of video, a text book, a course workbook, templates for getting started, and 2 coaching calls.',
        'instructor': 'Luca Leyva',
        'category': 'Kanban',
        'price': 299.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 10,
    },
]
